{% set name = "bioimageio.spec" %}
{% set version = "0.5.11.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bioimageio_spec-{{ version }}.tar.gz
  sha256: 6b5a659235fc59c9be654c8045b72d2d696f952ebfced69d64219b4d2708fb18

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - email-validator
    - annotated-types >=0.5.0,<1
    - email_validator
    - exceptiongroup
    - genericache ==0.5.2
    - httpx
    - imageio
    - loguru
    - markdown
    - numpy >=1.21
    - packaging >=17.0
    - platformdirs
    - pydantic >=2.10.3,<3
    - pydantic-core
    - pydantic-settings >=2.5,<3
    - python >={{ python_min }}
    - python-dateutil
    - rich
    - ruyaml
    - tifffile >=2020.7.4
    - tqdm
    - typing_extensions
    - zipp


test:
  imports:
    - bioimageio.spec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: Parser and validator library for BioImage.IO specifications
  dev_url: https://github.com/bioimage-io/spec-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
